// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Playlist': string;
  'Playlist_List': string;
}
export const cssExports: CssExports;
export default cssExports;
