// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AddInfoForSong': string;
  'LoadSong': string;
  'create': string;
}
export const cssExports: CssExports;
export default cssExports;
