// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SelectAuthor': string;
  'SelectAuthorModal': string;
}
export const cssExports: CssExports;
export default cssExports;
