// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'DivName': string;
  'DivNameHover': string;
  'PlaylistCard': string;
}
export const cssExports: CssExports;
export default cssExports;
