// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Albums': string;
  'AlbumsContainer': string;
  'AlbumsList': string;
}
export const cssExports: CssExports;
export default cssExports;
