// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MusicCard': string;
  'MusicCardAlbum': string;
  'MusicCardAuthor': string;
  'MusicCardInfo': string;
  'MusicCardLine': string;
  'MusicCardName': string;
}
export const cssExports: CssExports;
export default cssExports;
