// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Controls': string;
  'Controls2': string;
}
export const cssExports: CssExports;
export default cssExports;
