// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addSong': string;
  'addSongModal': string;
}
export const cssExports: CssExports;
export default cssExports;
