// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Select': string;
  'active': string;
}
export const cssExports: CssExports;
export default cssExports;
