// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'InputForm': string;
  'InputFormError': string;
}
export const cssExports: CssExports;
export default cssExports;
