// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AlbumModal': string;
  'AlbumPlay': string;
  'Info': string;
  'List': string;
}
export const cssExports: CssExports;
export default cssExports;
