// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ChangeView': string;
  'ChangeViewContent': string;
  'block': string;
  'line': string;
}
export const cssExports: CssExports;
export default cssExports;
