// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CreateAlbumPlaylistModal': string;
  'Data': string;
  'Img': string;
  'Info': string;
  'musicList': string;
}
export const cssExports: CssExports;
export default cssExports;
